# Generated by Django 6.1.1 on 2026-09-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_invoice_order"),
        ("orders", "0002_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="billing.invoice",
            ),
        ),
    ]
