# Generated by Django 6.1.1 on 2026-09-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("COOKING", "Cooking"),
                    ("READY", "Ready"),
                    ("SERVED", "Served"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
    ]
