# Generated by Django 6.1.1 on 2026-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
        ("customers", "0001_initial"),
        ("hotel", "0002_initial"),
        ("orders", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="display_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("display_number__isnull", False)),
                fields=("store", "display_number"),
                name="unique_display_number_per_store",
            ),
        ),
    ]
