# Generated by Django 6.1.1 on 2026-09-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_invoice_display_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-created_at"]},
        ),
    ]
