# Generated by Django 6.1.1 on 2026-09-09 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant"),
                            ("HOTEL", "Hotel"),
                            ("HOTEL_RESTAURANT", "Hotel + Restaurant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kathmandu", max_length=64)),
                ("currency", models.CharField(default="NPR", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant"),
                            ("HOTEL_PROPERTY", "Hotel Property"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_stores",
                        to="organizations.store",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "store_type"],
                        name="organizatio_organiz_6a188c_idx",
                    )
                ],
            },
        ),
    ]
