# Generated by Django 6.1.1 on 2026-09-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("hotel", "0001_initial"),
        ("orders", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folioline",
            name="source_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folio_lines",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="gueststay",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stays",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="gueststay",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="gueststay",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_stays",
                to="organizations.store",
            ),
        ),
        migrations.AddField(
            model_name="folio",
            name="guest_stay",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folio",
                to="hotel.gueststay",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="organizations.store",
            ),
        ),
        migrations.AddField(
            model_name="gueststay",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stays",
                to="hotel.reservation",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="organizations.store",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="hotel.room",
            ),
        ),
        migrations.AddField(
            model_name="gueststay",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stays",
                to="hotel.room",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_types",
                to="organizations.store",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="hotel.roomtype",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="hotel.roomtype"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("store", "number")},
        ),
    ]
