# Generated by Django 6.1.1 on 2026-09-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["number"]},
        ),
    ]
