# Generated by Django 6.1.1 on 2026-09-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_alter_room_options"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="roomtype",
            unique_together={("store", "name")},
        ),
    ]
