# Generated by Django 6.1.1 on 2026-09-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-created_at"]},
        ),
    ]
